const prefix = 'COURIERS_';

export default {
  FETCH_DETAILS: `${prefix}FETCH_DETAILS`,
  FETCH_DETAILS_COMPLETED: `${prefix}FETCH_DETAILS_COMPLETED`,
  SUBMIT: `${prefix}SUBMIT`,
  EVALUATE_DOCUMENTS_REVISION: `${prefix}EVALUATE_DOCUMENTS_REVISION`,
};
