const prefix = 'SETS_';

export default {
  FETCH_DETAILS: `${prefix}FETCH_DETAILS`,
  FETCH_SETS: `${prefix}FETCH_SETS`,
  FETCH_SETS_COMPLETED: `${prefix}FETCH_SETS_COMPLETED`,
  FETCH_SETS_BY_DISH_ID: `${prefix}FETCH_SETS_BY_DISH_ID`,
  FETCH_SETS_BY_DISH_ID_COMPLETED: `${prefix}FETCH_SETS_BY_DISH_ID_COMPLETED`,
  CLEAR: `${prefix}CLEAR`,
};
