const prefix = 'RESTAURANTS_';

export default {
  FETCH_DETAILS: `${prefix}FETCH_DETAILS`,
  FETCH_DETAILS_COMPLETED: `${prefix}FETCH_DETAILS_COMPLETED`,
  UPDATE_RESTAURANT_INFORMATION: `${prefix}UPDATE_RESTAURANT_INFORMATION`,
  UPDATE_RESTAURANT_INFORMATION_COMPLETED: `${prefix}UPDATE_RESTAURANT_INFORMATION_COMPLETED`,
  SUBMIT: `${prefix}SUBMIT`,
};
