const prefix = 'INFORMATION_PAGE_';

export default {
  FETCH_DETAILS: `${prefix}FETCH_DETAILS`,
  FETCH_DETAILS_COMPLETED: `${prefix}FETCH_DETAILS_COMPLETED`,
  CREATE_OR_UPDATE_INFORMATION_PAGE: `${prefix}CREATE_OR_UPDATE_INFORMATION_PAGE`,
  CREATE_OR_UPDATE_INFORMATION_PAGE_COMPLETED: `${prefix}CREATE_OR_UPDATE_INFORMATION_PAGE_COMPLETED`,
  CLEAR: `${prefix}CLEAR`,
  SUBMIT: `${prefix}SUBMIT`,
};
