const prefix = 'LAUNDRIES_';

export default {
  FETCH_DETAILS: `${prefix}FETCH_DETAILS`,
  FETCH_DETAILS_COMPLETED: `${prefix}FETCH_DETAILS_COMPLETED`,
  UPDATE_LAUNDRY_INFORMATION: `${prefix}UPDATE_LAUNDRY_INFORMATION`,
  UPDATE_LAUNDRY_INFORMATION_COMPLETED: `${prefix}UPDATE_LAUNDRY_INFORMATION_COMPLETED`,
  SUBMIT: `${prefix}SUBMIT`,
};
