const prefix = 'INFORMATION_PAGES_';

export default {
  FETCH_DETAILS: `${prefix}FETCH_DETAILS`,
  FETCH_INFORMATION_PAGES: `${prefix}FETCH_INFORMATION_PAGES`,
  FETCH_INFORMATION_PAGES_COMPLETED: `${prefix}FETCH_INFORMATION_PAGES_COMPLETED`,
  CLEAR: `${prefix}CLEAR`,
};
